version: '3.9'

services:
  zapstore-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zapstore-bot
    command: uvicorn app:app --host 0.0.0.0 --port 9000 --reload
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mongodb

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    command: ["postgres", "-c", "max_connections=1000"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: redis:latest
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  mongodb:
    image: mongo:latest
    container_name: zapstore-chatbot-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  evolution-api:
    container_name: evolution-api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances

    depends_on:
      - postgres
      - redis

volumes:
  evolution_instances:
  postgres_data:
  redis:
  mongodb_data:
