# Generated by Django 5.2.1 on 2025-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_document', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=555)),
                ('state', models.CharField(max_length=555)),
                ('zip_code', models.CharField(max_length=8)),
            ],
        ),
    ]
