# Generated by Django 5.2.1 on 2025-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=None, max_length=125, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_document',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
