import os
from dotenv import load_dotenv


load_dotenv


EVOLUTION_API_TOKEN = os.getenv('EVOLUTION_API_TOKEN')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
AUTHENTICATION_API_KEY = os.getenv('AUTHENTICATION_API_KEY')

DATABASE_ENABLED = os.getenv('DATABASE_ENABLED')
DATABASE_PROVIDER = os.getenv('DATABASE_PROVIDER')
DATABASE_CONNECTION_URI = os.getenv('DATABASE_CONNECTION_URI')
DATABASE_CONNECTION_CLIENT_NAME = os.getenv('DATABASE_CONNECTION_CLIENT_NAME')
DATABASE_SAVE_DATA_INSTANCE = os.getenv('DATABASE_SAVE_DATA_INSTANCE')
DATABASE_SAVE_DATA_NEW_MESSAGE = os.getenv('DATABASE_SAVE_DATA_NEW_MESSAGE')
DATABASE_SAVE_MESSAGE_UPDATE = os.getenv('DATABASE_SAVE_MESSAGE_UPDATE')
DATABASE_SAVE_DATA_CONTACTS = os.getenv('DATABASE_SAVE_DATA_CONTACTS')
DATABASE_SAVE_DATA_CHATS = os.getenv('DATABASE_SAVE_DATA_CHATS')
DATABASE_SAVE_DATA_LABELS = os.getenv('DATABASE_SAVE_DATA_LABELS')
DATABASE_SAVE_DATA_HISTORIC= os.getenv('DATABASE_SAVE_DATA_HISTORIC')

CACHE_REDIS_ENABLED = os.getenv('CACHE_REDIS_ENABLED')
CACHE_REDIS_URI = os.getenv('CACHE_REDIS_URI')
CACHE_REDIS_PREFIX_KEY = os.getenv('CACHE_REDIS_PREFIX_KEY')
CACHE_REDIS_SAVE_INSTANCES = os.getenv('CACHE_REDIS_SAVE_INSTANCES')
CACHE_LOCAL_ENABLED = os.getenv('CACHE_LOCAL_ENABLED')
