# Generated by Django 5.2.1 on 2025-05-30 01:59

"""
Custom migration to handle legacy Sales records without a related Customer.

Purpose:
1. Add the 'customer' field to the Sales model with null=True temporarily.
2. Populate existing Sales records with a default Customer.
3. Alter the field to be non-nullable (null=False).
"""

import django.db.models.deletion
from django.db import migrations, models


def add_customer(apps, schema_editor):
    """
    Fills existing Sales records with a default Customer before enforcing NOT NULL constraint.
    """
    Sales = apps.get_model('sales', 'Sales')
    Customer = apps.get_model('customers', 'Customer')

    # Create or retrieve a default customer
    generic_customer, _ = Customer.objects.get_or_create(
        email='customer@example.com',
        defaults={
            'name': 'Default Customer',
            'tax_document': '00000000000',
            'address': 'default address',
            'city': 'default city',
            'state': 'default state',
            'zip_code': '00000000'
        }
    )

    # Assign the default customer to all sales that don't have one
    Sales.objects.filter(customer__isnull=True).update(customer=generic_customer)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_email_alter_customer_tax_document'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(
                to='customers.Customer',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sales',
            ),
        ),
        migrations.RunPython(add_customer),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(
                to='customers.Customer',
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sales',
            ),
        ),
    ]
