from enum import Enum


class MessageType(Enum):
    FIRST_INTERACTION = 'FIRST_INTERACTION'
    SPECIFIC_PRODUCT = 'SPECIFIC_PRODUCT'
    INFORMATION_ABOUT_BRANDS = 'INFORMATION_ABOUT_BRANDS'
    CHEAPER_PRODUCTS = 'CHEAPER_PRODUCTS'
