# Generated by Django 5.2.1 on 2025-05-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inflows_options'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inflows',
            new_name='Inflow',
        ),
    ]
