version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: zapstore-api
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - zapstore-network

  db:
    image: postgres:latest
    container_name: zapstore-postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zapstore-network

volumes:
  postgres_data:

networks:
  zapstore-network:
    driver: bridge
