version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: zapstore-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - zapstore-network

  db:
    image: postgres:latest
    container_name: zapstore-postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zapstore-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: zapstore-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: zapstore
      RABBITMQ_DEFAULT_PASS: zapstore
    networks:
      - zapstore-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: zapstore-celery
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - api
      - rabbitmq
    environment:
      - CELERY_APP=core
      - CELERY_BROKER_URL=amqp://zapstore:zapstore@rabbitmq:5672//
    networks:
      - zapstore-network

  flower:
    image: mher/flower
    container_name: zapstore-flower
    command: celery flower --broker=amqp://zapstore:zapstore@rabbitmq:5672//
    environment:
      - CELERY_BROKER_URL=amqp://zapstore:zapstore@rabbitmq:5672//
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    networks:
      - zapstore-network

volumes:
  postgres_data:

networks:
  zapstore-network:
    driver: bridge
